= The myth of the management team
Page 25

A management team composed of representatives from each of an organization's core functions is meant to resolve cross-functional issues. When those issues are routine, the team may even succeed. But all too often, the team crumbles under pressure because they lack the skills necessary to communicate effectively and build shared understandings. Though they create an image of unity, each member holds reservations that they are not comfortable sharing with the group. When they state their opinions, they tend to assign blame and polarize the group further. When the group manages to reach a consensus, it does so only by relenting to the demands of an individual or by adopting a compromise that is insubstantial.

Routine decisions do not tax the team's underdeveloped teamwork abilities, whereas critical decisions exercise all of their weaknesses. Disillusioned with the "team," the mentality of <<I am my position>> prevails among members, who see each other as <<The enemy is out there>> ("the other team is just stonewalling us," or "they are an idiot"). When an individual suffers from <<The illusion of taking charge>>, they may thrust their opinions on the group to bring about a consensus, though they do not realize how this will further polarize the group.

